stages:
  - validate
  - test
  - build-base

variables:
  BUILD_VERSION: "$CI_COMMIT_TAG"
  BUILD_COMMIT_SHA: "$CI_COMMIT_SHA"
  OUTPUT_IMAGE: "lxd-zookeeper-$CI_COMMIT_TAG"
  IMAGE_REGISTRY: "barito-registry"
  COOKBOOK_PATHS: "./cookbooks"

before_script:
  - curl -s https://raw.githubusercontent.com/BaritoLog/cx-scripts/master/gitlabci-install-packer.sh | bash
  - wget https://github.com/jasoet/kscript-collections/releases/download/1.0.0/SimpleServerMock
  - chmod +x SimpleServerMock

validate:
  stage: validate
  script:
    - ./packer/packer validate ./packer.json
  tags:
    - bionic

test:
  stage: test
  variables:
    TEST_CONFIG_PATH: ./packer-test.json
  script:
    - ./SimpleServerMock -p 9797 -c mock-ygg.yml &> /dev/null &
    - export MOCK_PID=$!
    - ./packer/packer build $TEST_CONFIG_PATH
    - kill $MOCK_PID
  tags:
    - bionic

build-base:
  stage: build-base
  script:
    - curl -s https://raw.githubusercontent.com/BaritoLog/cx-scripts/master/gitlabci-build-base.sh | bash
    - curl -s https://raw.githubusercontent.com/BaritoLog/cx-scripts/master/gitlabci-copy-image.sh | bash
  tags:
    - bionic
    - lxd
    - lxc
  only:
    - tags
