---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
# Generate different types of nodes
<% { 'zookeeper' => 2 }.each do |name, n| %>
  <% ("01".."#{n}").each_with_index do |i, idx| %>
  - name: <%= name %>-<%= i %>
    run_list:
      - recipe[zookeeper::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      zookeeper:
        role: zookeeper
        hosts: ['zookeeper-01-ubuntu-1804.vagrantup.com', 'zookeeper-02-ubuntu-1804.vagrantup.com']
        my_id: <%= idx + 1 %>
        package_retries: 1
        yggdrasil:
          enabled: false
          host: ''
          api_version: 'v2'
          token: ''
          namespace: ''
          overrides: ''
  <% end %>
<% end %>
