---
driver:
  name: vagrant
  provision: true
  vagrantfiles:
    - Vagrantfile.rb
  synced_folders:
    - ["config", "/config"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
# Generate different types of nodes
<% { 'zookeeper' => 2 }.each do |name, n| %>
  <% ("01".."#{n}").each_with_index do |i, idx| %>
  - name: <%= name %>-<%= i %>
    run_list:
      - recipe[consul::default]
      - recipe[zookeeper::default]
      - recipe[zookeeper::consul_register]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      consul:
        run_as_server: false
        hosts: ["127.0.0.1"]
      zookeeper:
        role: zookeeper
        hosts: ['zookeeper-01-ubuntu-1804.vagrantup.com', 'zookeeper-02-ubuntu-1804.vagrantup.com']
        my_id: <%= idx + 1 %>
        package_retries: 1
        yggdrasil:
          enabled: true
          config_dir: '/opt/yggdrasil'
          configure_etc_hosts: false
  <% end %>
<% end %>
